name: main

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - uses: typst-community/setup-typst@v3.0.0
      - uses: RisingInIris2017/cjk-fonts-action@v1.0.7
      - run: mkdir images
      - run: python main.py
      - run: typst compile contentPro.typ contentPro.pdf
      - uses: actions/upload-artifact@v4
        with:
          path: |
            images/
            stare.txt
            contentPro.list
            contentPro.typ
            contentPro.pdf
            content.wikitext
          compression-level: 6
